version: '3.7'
services:
  allure-server:
    # For local debug #
    # build: .
    image: igur007/allure-server:2.13.6
    ports:
      - 8080:8080
    volumes:
      - ./tmp/allure:/allure/:rw
    environment:
      SPRING_PROFILES_ACTIVE: oauth
      # BASIC_AUTH_ENABLE: true
