version: '3.7'
services:
  allure-server:
    # For local debug #
    # build: .
    image: igur007/allure-server:v2.13.7
    ports:
      - 8080:8080
    volumes:
      - ./tmp/allure:/allure/:rw
    environment:
      SPRING_PROFILES_ACTIVE: oauth
      # BASIC_AUTH_ENABLE: true
