### Internal Spring Configuration
#server:
#  servlet:
#    context-path: "/server"
spring:
  servlet:
    multipart.max-file-size: 300MB
    multipart.max-request-size: 300MB
  datasource:
    url: "jdbc:h2:file:./allure/db"
    # H2 default username
    username: sa
    # H2 default password (empty)
    password:
  jpa:
    database: H2
    show-sql: false
    hibernate.ddl-auto: update
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: basic

vaadin.urlMapping: "/ui/*"
server.port: ${PORT:8080}

### Security
basic:
  auth:
    username: admin
    password: admin
    enable: false

### App Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# #################
# Deprecated format. Not supported!
# #################
# allure:
#   results.dir: allure/results/
#   reports:
#     dir: allure/reports/
#     path: reports/
#     history.level: 20
#   support.old.format: false
#   date.format: "yy/MM/dd HH:mm:ss"
allure:
  title: "Allure Report"
  # FROM URL: https://avatars.githubusercontent.com/u/16944358?v=4
  # FROM FILE: file:/images/logo.png
  logo: ""
  resultsDir: allure/results/
  reports:
    dir: allure/reports/
    path: reports/
    history-level: 20
  support-old-format: false
  date-format: "yy/MM/dd HH:mm:ss"
  clean:
    dryRun: false
    time: "00:00"
    ageDays: 30
    paths:
      - path: "manual_uploaded"
        ageDays: 10
  server-base-url:
logging:
  level:
    root: INFO
    org.atmosphere: WARN # Vaadin (GUI) Server
    org.springframework: INFO
    org.springframework.core: WARN
    org.springframework.beans.factory.support: WARN
    qa.allure: INFO # Allure Server Logs
    qa.allure.api: DEBUG

tms:
  enabled: false
  host: tms.localhost
  api-base-url: https://${tms.host}/api
  token: "my-token"
  issue-key-pattern: "[A-Za-z]+-\\d+"
  dry-run: false
