apiVersion: v1
kind: Service
metadata:
  name: allure-server-service
  labels:
  {{- include "allure-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "allure-server.selectorLabels" . | nindent 4 }}
