# templates/pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allure-server-store-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.allureServer.persistence.allureSize }}
