# templates/pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ext-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.allureServer.persistence.extSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allure-server-store-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.allureServer.persistence.allureSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
