# values.yaml

allureServer:
  image: "igur007/allure-server:v2.13.8"
  replicas: 1
  service:
    port: 8080
  env:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://allure-server-postgresql:5432/allure"
    SPRING_DATASOURCE_USERNAME: "postgres"
    SPRING_DATASOURCE_PASSWORD: "postgres"
    SPRING_JPA_DATABASE: "postgresql"
    SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    TMS_ENABLED: "false"  # Changed to string
    TMS_HOST: "jira.localhost"
    TMS_TOKEN: "<token-here>"
    TMS_DRYRUN: "false"  # Changed to string
  persistence:
    extSize: "1Gi"
    allureSize: "5Gi"

postgresql:
  enabled: true

  auth:
    username: "postgres"
    password: "postgres"
    database: "allure"
    existingSecret: ""
  primary:
    persistence:
      size: 5Gi
